=== VijayaDurgaN/policy-details-soap/src/main/resources/xsd/policy-details.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://allstate.com/policy"
           targetNamespace="http://allstate.com/policy" elementFormDefault="qualified">

    <xs:element name="GetPolicyDetailsRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="claimNumber">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value='10000000'/>
                            <xs:maxInclusive value='99999999'/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetPolicyDetailsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PolicyDetails" type="tns:PolicyDetails"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PolicyDetails">
        <xs:sequence>
            <xs:element name="claimNumber" type="xs:int"/>
            <xs:element name="policyHolderName" type="xs:string"/>
            <xs:element name="policyNumber" type="xs:int"/>
            <xs:element name="coverageName" type="xs:string"/>
            <xs:element name="coverageLimit" type="xs:int"/>
            <xs:element name="deductible" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== VijayaDurgaN/policy-details-soap/examplefiles/Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<GetPolicyDetailsResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xmlns="http://allstate.com/policy"
                          xsi:schemaLocation="http://allstate.com/policy policy-details.xsd">
    <PolicyDetails>
        <claimNumber>123</claimNumber>
        <policyHolderName>Spring in28minutes</policyHolderName>
        <policyNumber>123456</policyNumber>
        <coverageName>abc</coverageName>
        <coverageLimit>200000</coverageLimit>
        <deductible>10000</deductible>
    </PolicyDetails>
</GetPolicyDetailsResponse>
